name: test-coverage
on:
  push:
  pull_request:
jobs:
  test-coverage:
    runs-on: [self-hosted, linux]
    env:
      NODE_V8_COVERAGE: coverage/tmp
      PROFILE: default
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm i
          fi
      - name: Prepare coverage directory
        run: mkdir -p coverage/tmp

      - name: ESM syntax check (.mjs)
        run: |
          set -euo pipefail
          find app -type f -name '*.mjs' -print0 | xargs -0 -r -n1 node --check
      - name: JSX syntax check (.js/.jsx)
        run: |
          set -euo pipefail
          npx --yes -p eslint -p @babel/eslint-parser -p @babel/core -p @babel/plugin-syntax-jsx \
            eslint --no-eslintrc \
            --parser @babel/eslint-parser \
            --parser-options '{ "ecmaVersion": 2022, "sourceType": "module", "requireConfigFile": false, "babelOptions": { "plugins": ["@babel/plugin-syntax-jsx"] } }' \
            --ext .js,.jsx app
      - name: Run tests (Node runner)
        run: npm run -s test
      - name: Coverage summary (text)
        run: npx c8 report --reporter=text
      - name: Coverage artifact (lcov)
        run: npx c8 report --reporter=lcov
      - name: Upload lcov
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov-${{ matrix.profile }}
          path: coverage/lcov.info
          if-no-files-found: ignore
