name: test-coverage
on:
  push:
  pull_request:
jobs:
  test-coverage:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        profile: [serverless, longrun]
    env:
      NODE_V8_COVERAGE: coverage/tmp
      PROFILE: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm i
          fi
      - name: Prepare coverage directory
        run: mkdir -p coverage/tmp
      - name: Run tests (Node runner)
        run: npm run -s test
      - name: Coverage summary (text)
        run: npx c8 report --reporter=text
      - name: Coverage artifact (lcov)
        run: npx c8 report --reporter=lcov
      - name: Upload lcov
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov-${{ matrix.profile }}
          path: coverage/lcov.info
          if-no-files-found: ignore
